server:
  port: 8081
spring:
  application:
    name: user-service-01
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mybatis
    username: root
    password: dcgj
mybatis:
  mapper-locations: classpath:mappers/**.xml
logging:
  level:
    com.xuhao.service: debug
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    register-with-eureka: true