server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://localhost:10086/eureka
    registry-fetch-interval-seconds: 5
    fetch-registry: true
zuul:
  routes:
    user-service-01: /user-service-01/**